### ISSUE TITLE
why 4 annotations channels

### ISSUE THREAD

**Issue by mictadlo** [skptic/tuxedo-nf#3]
Hello,
why it necessary to have 4 annotations channels [declared](https://github.com/skptic/tuxedo-nf/blob/master/tuxedo.nf#L108) in `file "*.gtf" into annotations1, annotations2, annotations3, annotations4`?

Thank you in advance,

Michal

**Comment by evanfloden** [comment]
It was previously required but the in a later release of Nextflow, if a process is only run once then this requirement for multiple channels is not needed. 

I will be updating this pipeline in the next days to reflect this.
