### ISSUE TITLE
Reducing of job running parallel

### ISSUE THREAD

**Issue by mictadlo** [skptic/tuxedo-nf#6]
Hi, how is it possible to reduce the amount of jobs running parallel?

Thank you in advance

Michal

**Comment by pditommaso** [comment]
Are you running it locally or by using a cluster scheduler ?

**Comment by mictadlo** [comment]
Locally

**Comment by pditommaso** [comment]
You can use the `-qs` command line to define the max number of tasks processes in parallel

**Comment by mictadlo** [comment]
Thank you it works.
